version: 0.2

phases:
  install:
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm ci
      - cd ..
      - echo "Installing frontend dependencies..."
      - cd frontend && npm ci
      - cd ..
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Building backend..."
      - cd backend && npm run build
      - cd ..
      - echo "Building frontend..."
      - cd frontend && npm run build
      - cd ..
  post_build:
    commands:
      - echo "Build completed successfully!"
